dist: xenial
env:
  global:
    - PATH=/opt/python/3.7.1/bin:$PATH
language: matlab
install:  
  # Check the python version and update pip
  - python -V
  - python -m pip install --upgrade pip
  
  # Install MHKiT-Python
  - python -m pip install mhkit
  
  # Install MHKiT-MATLAB
  - python -m pip install -e .

script:
  # Look for linalg
  - ls /opt/python/3.7.1/lib/python3.7/site-packages/numpy/linalg/
  
  # Try and preload numpy lapack
  #- export LD_LIBRARY_PATH=/opt/python/3.7.1/lib
  #- export LD_PRELOAD=/opt/python/3.7.1/lib/python3.7/site-packages/numpy/linalg/lapack_lite.cpython-37m-x86_64-linux-gnu.so

  # Show matlab and python version for the build
  - matlab -batch "py.sys.setdlopenflags(int32(10)), version, pyversion, version('-blas')"
  
  # Installs mhkit toolbox in matlab, goes to the test folder, imports mhkit, 
  # then runs the test script
  - >
    matlab -batch 
    "py.sys.setdlopenflags(int32(10)),
    matlab.addons.toolbox.installToolbox('mhkit.mltbx'),
    cd mhkit/tests/,
    import mhkit.*,
    results = runTests(),
    assertSuccess(results)"
