language: minimal

stages:
  - test
  
jobs:
  include:
    - stage: test
      language: matlab
      before_install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo add-apt-repository main
        - sudo add-apt-repository universe
        - sudo add-apt-repository restricted
        - sudo add-apt-repository multiverse  
        - sudo add-apt-repository ppa:deadsnakes/ppa -y
        - sudo apt-get update
        - sudo apt install python3.7
        - python3.7 --version
        - sudo apt install python3.7-distutils
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python3.7 get-pip.py
      install:  
        - python3.7 -m pip install -e .
        - git clone --depth 1 https://github.com/psf/requests.git requests
        - cd requests
        - python3.7 -m pip install -e .
        - cd ..
        - git clone --depth 1 https://github.com/MHKiT-Software/MHKiT-Python mhkit-python
        - cd mhkit-python
        - python3.7 -m pip install -e .

      script:
        - python3.7 -m pip install -e .
        - python3.7 -c "import mhkit; print('hello world')"
        - cd ..
        - matlab -batch "ls"
        - realpath mhkit.mltbx
        - python3.7 -m pip install -e .
        - python3.7 -c "import mhkit; print('hello world')"
        - python3.7 -c "import sys; print(sys.executable)"
        - matlab -batch "version, pyversion"
        - matlab -batch "[x,y]=circular(30)"
        - matlab -batch "matlab.addons.toolbox.install('mhkit.mltbx')"
        - matlab -batch "pyversion('/usr/bin/python3.7'), pyversion, import mhkit.*"
        
      if: branch = master
