language: minimal

stages:
  - test
  
jobs:
  include:
    - stage: test
      language: matlab
      before_install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo apt-get install python3.7
        - python3.7 --version
      install: 
        - git clone --depth 1 https://github.com/MHKiT-Software/MHKiT-Python mhkit-python
        - cd mhkit-python
        - sudo -H pip install -e .
      script: 
        - matlab -batch "import mhkit.*; matlab.addons.install('mhkit.mltbx'); runMatlabTests(); results = runTests('reportHTML', false, 'reportPDF', false), assertSuccess(results);"
      if: branch = master
