language: minimal

stages:
  - test
  
jobs:
  include:
    - stage: test
      language: matlab
      before_install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo add-apt-repository main
        - sudo add-apt-repository universe
        - sudo add-apt-repository restricted
        - sudo add-apt-repository multiverse  
        - sudo add-apt-repository ppa:deadsnakes/ppa -y
        - sudo apt-get update
        - sudo apt install python3.9
        - python3.9 --version
      install: 
        - git clone --depth 1 https://github.com/MHKiT-Software/MHKiT-Python mhkit-python
        - cd mhkit-python
        - sudo -H pip install -e .
      script: 
        - matlab -batch "import mhkit.*; matlab.addons.install('mhkit.mltbx'); runMatlabTests(); results = runTests('reportHTML', false, 'reportPDF', false), assertSuccess(results);"
      if: branch = master
