
language: matlab
install:
  # We do this conditionally because it saves us some downloading if the version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
  # Add Conda Forge
  - conda config --append channels conda-forge
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=3.7 pandas numpy scipy matplotlib requests
  - conda install pip
  - conda activate test-environment
  - python setup.py install
  
  # get python path
  - which python

  # install pecos
  - python -m pip install pecos
  
  # install libpng and zlib
  - sudo apt-get install libpng-dev
  
  #install zlib
  - apt-cache search zlib1g
  - apt list policy zlib1g
  - apt list policy zlib1g-dbg
  - apt list policy zlib1g-dev
  - sudo apt-get install zlib1g=1.2.9 -y --allow-downgrades

  # Install mhkit-python
  - git clone --depth 1 https://github.com/MHKiT-Software/MHKiT-Python mhkit-python
  - cd mhkit-python
  - python -m pip install -e .
  - cd ..
  - python -m pip install -e .

script:
  # Your test script goes here
  - matlab -batch "pyversion, matlab.addons.toolbox.installToolbox('/home/travis/build/mfaltas-sandia/MHKiT-MATLAB/mhkit.mltbx'), [x,y]=circular(30)"
