language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"
install:
  # We do this conditionally because it saves us some downloading if the version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
  # Add Conda Forge
  - conda config --append channels conda-forge
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pandas numpy scipy matplotlib requests
  - conda install pip
  - python$TRAVIS_PYTHON_VERSION -m pip install pecos
  - conda activate test-environment
  - python setup.py install
  
  # Install mhkit-python
  - git clone --depth 1 https://github.com/MHKiT-Software/MHKiT-Python mhkit-python
  - cd mhkit-python
  - sudo python$TRAVIS_PYTHON_VERSION -m pip install -e .


script:
  # Your test script goes here
