name: MHKiT-MATLAB Code Compatibility Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  main:
    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", 3.11]
        matlab-version: [R2021b, R2022a, R2022b, R2023a, R2023b]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out MHKiT-MATLAB
        uses: actions/checkout@v4

      - name: Setup MATLAB Path on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo "LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6" >> "$GITHUB_ENV"

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.matlab-version }}

      - name: Build file to run code compatability report
        shell: bash
        run: echo "version,
          addpath(genpath('mhkit')),
          results = runCodeCompatibilityReport()" >> run.m

      - name: Output run.m
        shell: bash
        run: cat run.m

      # This is a good idea but does not work because you cannot explicitly set the python execution mode
      #   - name: Run MHKiT-MATLAB Unit Tests
      #     uses: matlab-actions/run-tests@v1
      #     with:
      #         select-by-folder: mhkit/tests

      - name: Run MATLAB Unit Tests
        uses: matlab-actions/run-command@v1
        with:
          command: run
          startup-options: -noFigureWindows
