name: MATLAB | Windows Mac Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Run MATLAB Tests on GitHub-Hosted Runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
            
      - name: Update and install Python packages
        run: |
            python -m pip install --upgrade pip wheel
            python -m pip install mhkit --upgrade
# TODO: install mhkit from source instead
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      
#      - name: Query Python version used by MATLAB
#        uses: matlab-actions/run-command@v1
#        with:
#            command: pyversion()

# This can cause segmentation violations
#      - name: List installed MATLAB addons
#        uses: matlab-actions/run-command@v1
#        with:
#            command: matlab.addons.installedAddons

# This can cause segmentation violations
#      - name: List installed MATLAB toolboxes
#        uses: matlab-actions/run-command@v1
#        with:
#            command: matlab.addons.toolbox.installedToolboxes
# alternative: command: ver
              
#      - name: Toggle off all pre-installed toolboxes
#        uses: matlab-actions/run-command@v1
#        with:
#            command: addpath('mhkit/utils'), uninstall_all_toolboxes
#              
#      - name: Uninstall h5py, for fixing HDF5 issue
#        run: |
#            python pip uninstall h5py -y
#
      - name: Install MHKiT toolbox in MATLAB
        uses: matlab-actions/run-command@v1
        with:
            command: matlab.addons.toolbox.installToolbox('mhkit.mltbx')
#
#      - name: Uninstall MHKiT, for fixing HDF5 issue
#        run: |
#            python -m pip uninstall mhkit -y
#      
#      - name: Re-install MHKiT, for fixing HDF5 issue
#        run: |
#            python -m pip install mhkit
          
#      - name: Change execution mode to out-of-process
#        uses: matlab-actions/run-command@v1
#        with:
#            command: pyenv("ExecutionMode","OutOfProcess")

      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: mhkit; mhkit_python_utils; examples/data
          select-by-tag: DebuggingActions
          test-results-junit: mhkit/tests/results.xml
          code-coverage-cobertura: mhkit/tests/results.xml
