name: Unit Tests

on:
  push:
    branches: [ master, develop, ebbflodd ]
  pull_request:
    branches: [ master, develop, ebbflodd ]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]
        mat_release: [latest]
        include:
          - os: ubuntu-latest
            mat_release: R2021a
    runs-on: ${{ matrix.os }}
    env:
      mhkit-python-dir: 'MHKiT-Python'
    steps:
      - name: Test Output
        shell: bash
        run: echo "Hello World!"
     