name: MHKiT-MATLAB Unix Unit Tests

on:
  push:
    branches: [ master, develop, ebbflood ]
  pull_request:
    branches: [ master, develop, ebbflood ]

jobs:
  main:
    strategy:
      fail-fast: false

      # Expecting 2 * 4 * 7 - (13 * 2) = 30 jobs
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", 3.11]
        matlab-version: [R2020b, R2021a, R2021b, R2022a, R2022b, R2023a, R2023b]
        exclude:
            - matlab-version: R2023b
              python-version: 3.8
            - matlab-version: R2023a
              python-version: 3.11
            - matlab-version: R2022b
              python-version: 3.11
            - matlab-version: R2022a
              python-version: 3.11
            - matlab-version: R2022a
              python-version: "3.10"
            - matlab-version: R2021b
              python-version: 3.11
            - matlab-version: R2021b
              python-version: "3.10"
            - matlab-version: R2021a
              python-version: 3.11
            - matlab-version: R2021a
              python-version: "3.10"
            - matlab-version: R2021a
              python-version: 3.9
            - matlab-version: R2020b
              python-version: 3.11
            - matlab-version: R2020b
              python-version: "3.10"
            - matlab-version: R2020b
              python-version: 3.9
    
    runs-on: ${{ matrix.os }}

    env:
      mhkit-python-dir: 'MHKiT-Python'
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup MHKiT Dependencies on macOS
        run: brew install hdf5 netcdf4
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Setup MHKiT Dependencies on ubuntu
        run: sudo apt install libhdf5-serial-dev libnetcdf-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Print Python executable
        run: python -c "import sys; print(sys.executable)"

      - name: Print Python Version
        run: python --version

      - name: Check out MHKiT-MATLAB
        uses: actions/checkout@v4

      - name: Check out MHKiT-Python
        uses: actions/checkout@v4
        with:
          repository: 'MHKiT-Software/MHKiT-Python'
          path: ${{env.mhkit-python-dir}}
        
      - name: pip install mhkit module from source
        run: "pip install -e ."
        working-directory: ${{env.mhkit-python-dir}}

      - name: pip install mhkit-python-utils module from source
        run: pip install -e .

      - name: List installed pip modules
        run: pip freeze

      # - name: Test MHKiT-Python
      #   run: |
      #     pip install nose pytest
      #     nosetests -v --traverse-namespace mhkit
      #   working-directory: ${{env.mhkit-python-dir}}
      # #   if: always() && steps.runTests.outcome == 'failure'

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab-version }}

      # OutOfProcess allows MATLAB python to access libraries that use Cython (h5py).
      # So far, this is necessary on linux, more investigation is needed on MacOS
      - name: Set MATLAB OutOfProcess Python execution mode
        shell: bash
        run: echo "pyenv('ExecutionMode', 'OutOfProcess')" >> run.m
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Add MATLAB test commands
        shell: bash
        run: echo "version, 
                   addpath(genpath('mhkit')), 
                   import matlab.unittest.TestSuite, 
                   import matlab.unittest.TestRunner, 
                   testFolder = ['mhkit' filesep 'tests'], 
                   suite = TestSuite.fromFolder(testFolder), 
                   runner = TestRunner.withTextOutput,
                   results = runner.run(suite), 
                   assertSuccess(results)" >> run.m

      - name: Output run.m
        shell: bash
        run: cat run.m

    # This is a good idea but does not work because you cannot explicitly set the python execution mode
    #   - name: Run MHKiT-MATLAB Unit Tests
    #     uses: matlab-actions/run-tests@v1
    #     with:
    #         select-by-folder: mhkit/tests

      - name: Run MATLAB Unit Tests
        uses: matlab-actions/run-command@v1
        with:
          command: run
          startup-options: -noFigureWindows

        

      