name: MHKiT-MATLAB Windows Unit Tests

on:
  push:
    branches: [master, develop, ebbflood]
  pull_request:
    branches: [master, develop, ebbflood]

jobs:
  cache_population:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.9]
        matlab-version: [R2022a]
    runs-on: ${{ matrix.os }}

    env:
      mhkit-python-dir: "MHKiT-Python"
      MHKIT_PYTHON_VERSION: '0.7.0'
    steps:
      - name: Install/Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: mhkit_conda_env
          channels: conda-forge

      # This is necessary to fix any issues with netcdf4 and hdf5 headers
      - name: "Conda install netcdf4, hdf5"
        run: |
          conda activate mhkit_conda_env
          conda install numpy cython pip pytest hdf5 libnetcdf cftime netcdf4 --strict-channel-priority

      - name: Check out MHKiT-MATLAB
        uses: actions/checkout@v4

      # - name: Check out MHKiT-Python
      #   uses: actions/checkout@v4
      #   with:
      #     repository: "MHKiT-Software/MHKiT-Python"
      #     path: ${{env.mhkit-python-dir}}

      # - name: pip install mhkit from source
      #   working-directory: ${{env.mhkit-python-dir}}
      #   run: |
      #     conda activate mhkit_conda_env
      #     pip3 install -e .

      - name: pip install mhkit from pypi
        shell: bash -l {0}
        run: |
          conda activate mhkit_conda_env
          pip install -e .

      - name: pip install mhkit-python-utils module from source
        run: |
          conda activate mhkit_conda_env
          pip install -e .

      # Create the cache and add a dummy file
      # The dummy file ensures that the artifact download
      - name: Setup mhkit_webread_cache
        shell: bash -l {0}
        run: |
          mkdir mhkit_webread_cache
          touch mhkit_webread_cache/test.txt
          echo "Hello World" > mhkit_webread_cache/test.txt

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-version }}

      - name: Configure MATLAB pyenv Version and ExecutionMode
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: >
          "pyenv(Version='{0}', ExecutionMode='OutOfProcess')" -f (python -c "import sys; print(sys.executable)") | Out-File -FilePath run.m

      - name: Check Python System Path
        # if: ${{ matrix.os == 'windows-latest' }}
        shell: bash -l {0}
        run: |
          echo "py.sys.path" >> run.m

      - name: Add MATLAB test commands
        shell: bash
        run: echo "version,
          addpath(genpath('mhkit')),
          import matlab.unittest.TestSuite,
          import matlab.unittest.TestRunner,
          testFolder = ['mhkit' filesep 'tests'],
          suite = TestSuite.fromFolder(testFolder),
          runner = TestRunner.withTextOutput,
          results = runner.run(suite),
          assertSuccess(results)" >> run.m

      - name: Output Run.m
        shell: bash
        run: cat run.m

      - name: Run MHKiT-MATLAB Unit Tests
        uses: matlab-actions/run-command@v2
        with:
          command: run
          startup-options: -noFigureWindows

      - name: Save mhkit_webread_cache directory as an artifact
        uses: actions/upload-artifact@v4
        with:
          # GitHub Action "Name" of artifact
          name: mhkit_webread_cache
          # Filesystem path of directory
          path: mhkit_webread_cache

  main:
    needs: cache_population
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9, "3.10", 3.11]
        matlab-version: [R2021b, R2022a, R2022b, R2023a, R2023b, R2024a]
        # R2022b and above have a windows specific error related to the MATLAB/Python interface
        # matlab-version: [R2021b, R2022a]
        exclude:
          - matlab-version: R2022a
            python-version: 3.9
          - matlab-version: R2023b
            python-version: 3.8
          - matlab-version: R2023a
            python-version: 3.11
          - matlab-version: R2022b
            python-version: 3.11
          - matlab-version: R2022a
            python-version: 3.11
          - matlab-version: R2022a
            python-version: "3.10"
          - matlab-version: R2021b
            python-version: 3.11
          - matlab-version: R2021b
            python-version: "3.10"
          - matlab-version: R2021a
            python-version: 3.11
          - matlab-version: R2021a
            python-version: "3.10"
          - matlab-version: R2021a
            python-version: 3.9
          - matlab-version: R2020b
            python-version: 3.11
          - matlab-version: R2020b
            python-version: "3.10"
          - matlab-version: R2020b
            python-version: 3.9
          - matlab-version: R2024a
            python-version: 3.8
    runs-on: ${{ matrix.os }}

    env:
      mhkit-python-dir: "MHKiT-Python"
      MHKIT_PYTHON_VERSION: ${{  matrix.mhkit-python-version }}
    steps:
      - name: Install/Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: mhkit_conda_env
          channels: conda-forge

      # - name: "Conda install h5py, netcdf4, and cython"
      #   run: |
      #     conda activate mhkit_conda_env
      #     conda install -c conda-forge h5py netcdf4 cython

      - name: "Conda install h5py, netcdf4, and cython"
        run: |
          conda activate mhkit_conda_env
          conda install numpy cython pip pytest hdf5 libnetcdf cftime netcdf4 --strict-channel-priority

      - name: Output python executable
        shell: bash -l {0}
        run: |
          conda activate mhkit_conda_env
          python -c "import sys; print(sys.executable)"

      - name: Print Python Version
        shell: bash -l {0}
        run: |
          conda activate mhkit_conda_env
          python --version

      # - name: Output python executable
      #   run: |
      #     conda activate mhkit_conda_env
      #     python -c "import sys; print(sys.executable)"

      # - name: Print Python Version
      #   run: |
      #     conda activate mhkit_conda_env
      #     python --version

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Output python executable
      #   run: |
      #     python -c "import sys; print(sys.executable)"

      # - name: Print Python Version
      #   run: |
      #     python --version

      - name: Check out MHKiT-MATLAB
        uses: actions/checkout@v4

      # - name: Check out MHKiT-Python
      #   uses: actions/checkout@v4
      #   with:
      #     repository: "MHKiT-Software/MHKiT-Python"
      #     path: ${{env.mhkit-python-dir}}

      - name: pip install mhkit from source
        working-directory: ${{env.mhkit-python-dir}}
        run: |
          conda activate mhkit_conda_env
          pip3 install -e .

      - name: pip install mhkit from source
        working-directory: ${{env.mhkit-python-dir}}
        run: |
          pip install -e .

      # - name: pip install mhkit-python-utils module from source
      #   run: |
      #     pip3 install mhkit

      - name: pip install mhkit-python-utils module from source
        run: |
          conda activate mhkit_conda_env
          pip3 install -e .

      # - name: pip install mhkit-python-utils module from source
      #   run: |
      #     pip3 install -e .

      - name: List installed pip modules
        run: |
          conda activate mhkit_conda_env
          pip3 freeze

      - name: Print MHKiT-Python Version
        shell: bash -l {0}
        run: |
          conda activate mhkit_conda_env
          python -c "import mhkit; print(mhkit.__version__)"

      - name: LS Conda Env Dir
        shell: bash -l {0}
        run: |
          ls C:\Miniconda\envs\MHKIT_CONDA_ENV

      # - name: Echo Path
      #   shell: bash -l {0}
      #   run: |
      #     echo $GITHUB_PATH

      - name: Tree Conda Env Dir
        shell: bash -l {0}
        run: |
          tree C:\Miniconda\envs\MHKIT_CONDA_ENV

      - name: Add anaconda env to path
        shell: bash -l {0}
        run: |
          echo C:\Miniconda\envs\MHKIT_CONDA_ENV >> $GITHUB_PATH

      # - name: Echo Path
      #   shell: bash -l {0}
      #   run: |
      #     echo $GITHUB_PATH

      - name: Verify MHKiT-Python Operation
        shell: bash -l {0}
        run: |
          conda activate mhkit_conda_env
          python -c "import mhkit; [ED, AP] = mhkit.river.performance.circular(30); print(ED); print(AP);"

      - name: Download mhkit_webread_cache artifact
        uses: actions/download-artifact@v4
        with:
          name: mhkit_webread_cache
          path: mhkit_webread_cache

      - name: Display structure mhkit_webread_cache
        run: ls -R
        working-directory: .

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-version }}

      # OutOfProcess works reliably on linux and macos, on Windows
      # OutOfProcess fails with error:
      # Caught "std::exception" Exception message is:
      # Unable to launch Simple server: Unable to launch C:\Program Files\MATLAB\R2023b\interprocess\bin\win64\pycli\MATLABPyHost.exe
      # because: Peer process exited before transport type handshake. Exit status: 3221226505
      # ERROR: MATLAB error Exit Status: 0x00000001
      # exit status 1

      # - name: Add Python Dir to Path
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   shell: pwsh
      #   run: >
      #     "setenv('path', ['{0}', getenv('path')]);" -f (python -c "import sys; import os; print(os.path.dirname(sys.executable))") | Out-File -FilePath run.m -Append

      - name: Add Python Dir to Path
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: >
          "conda activate MHKIT_CONDA_ENV; setenv('path', ['{0}', getenv('path')]);" -f (python -c "import sys; import os; print(os.path.dirname(sys.executable))") | Out-File -FilePath run.m -Append

      # - name: Configure MATLAB pyenv Version and ExecutionMode
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   shell: pwsh
      #   run: >
      #     "pyenv(Version='{0}', ExecutionMode='InProcess')" -f (python -c "import sys; print(sys.executable)") | Out-File -FilePath run.m

      - name: Configure MATLAB pyenv Version and ExecutionMode
        # if: ${{ matrix.os == 'windows-latest' }}
        shell: bash -l {0}
        run: |
          conda activate mhkit_conda_env
          printf "pyenv(Version='%s', ExecutionMode='OutOfProcess')" $(python -c "import sys; print(sys.executable)") >> run.m

      - name: Check Python System Path
        # if: ${{ matrix.os == 'windows-latest' }}
        shell: bash -l {0}
        run: |
          echo "py.sys.path," >> run.m

      - name: Add MATLAB test commands
        shell: bash
        run: echo "version,
          pyenv,
          addpath(genpath('mhkit')),
          import matlab.unittest.TestSuite,
          import matlab.unittest.TestRunner,
          testFolder = ['mhkit' filesep 'tests'],
          suite = TestSuite.fromFolder(testFolder),
          runner = TestRunner.withTextOutput,
          results = runner.run(suite),
          assertSuccess(results)" >> run.m

      - name: Output Run.m
        shell: bash
        run: cat run.m

      - name: Run MHKiT-MATLAB Unit Tests
        uses: matlab-actions/run-command@v2
        with:
          command: run
          startup-options: -noFigureWindows
